### ISSUE TITLE
peda-arm on termux ( Android )

### ISSUE THREAD

**Issue by Hax4us** [alset0326/peda-arm#10]
hii i was struggling with original peda but then google landed me here and i found some hope but i am facing some issues 

![Screenshot_2021-04-17-10-23-06-861_com termux](https://user-images.githubusercontent.com/30441647/115102272-75b24f80-9f67-11eb-93ce-832bbe181505.jpg)
as you can see output of `context code` & `context reg`is empty

**Comment by alset0326** [comment]
hi there, you can use `pset option debug on` to open the debug message and use `pflush` to force flush output buffer. Then maybe I can find out what happened

**Comment by Hax4us** [comment]
ok so i got it the root cause is https://github.com/alset0326/peda-arm/blob/edbf2f154392f5f2eb01f99e576d2f9c87de045f/peda/core.py#L395
as `/proc/version` is not readable in un-rooted devices
so just put a condition to check if host is termux or not ( maybe by checking if directory **/data/data/com.termux** exists or not)

I can give a PR if you want :)

**Comment by alset0326** [comment]
Yes please! thank you so much

**Comment by Hax4us** [comment]
closing with https://github.com/alset0326/peda-arm/pull/11
