### ISSUE TITLE
context stack doesn't seem to work

### ISSUE THREAD

**Issue by pwnipc** [alset0326/peda-arm#12]
hi, the stack data doesn't get printed on hitting a breakpoint, running either context all or context stack.
![image](https://user-images.githubusercontent.com/60155767/219018606-bb0c5812-bd04-4d79-92b9-6173c28a1489.png)
```context stack```
![image](https://user-images.githubusercontent.com/60155767/219019060-bd6d033f-6991-48e6-a85d-d7495c2ac8df.png)

**Comment by alset0326** [comment]
Can you run `pset option debug on` and then show me the `context stack` output?
@Chal13W1zz

**Comment by pwnipc** [comment]
appears to be some int overflow
![image](https://user-images.githubusercontent.com/60155767/219308366-40bd014e-4a9a-46e2-9347-0d9438a2058a.png)

**Comment by alset0326** [comment]
I think it's because your python is 32-bit, you may modify line 2914 in core.py to temporally solve this problem.
```python
for value in range(0, step * count, step):
    value += address
```

**Comment by pwnipc** [comment]
This does it, thanks.
![image](https://user-images.githubusercontent.com/60155767/219350899-64efad28-2a1e-43ae-879e-2f639ff98ece.png)
