### ISSUE TITLE
Cloning the peda-arm project and executing pattc..pattx does not work (temp. fix available)

### ISSUE THREAD

**Issue by rusttest5578** [alset0326/peda-arm#15]
Hello,
I have discovered a bug which I was not aware of #14  the time I opened the PR. Specifically, if I clone just the project peda-arm and execute pattc it does not work as intended. This is because several library files are missing from the peda classic repo.

It worked for me because I already had the peda classic repo installed and on top of it I installed the peda-arm.
So, it only works if we do:
`$ git clone https://github.com/longld/peda.git ~/peda`
`$ git clone https://github.com/alset0326/peda-arm.git ~/peda-arm`
`$ echo "source ~/peda-arm/peda-arm.py" >> ~/.gdbinit`

I could probably try to solve this and create a standalone peda-arm but I require to install all the lib files in peda-arm from peda classic.
What should I do?

**Comment by alset0326** [comment]
I'll check it later and try to fix it🙂

**Comment by rusttest5578** [comment]
I made a PR with the fix. The commands should work now without having to install peda classic first. I tested this in my mac on a Debian machine.

**Comment by alset0326** [comment]
see #17 

peda is designed not to be installed as a python package. It only need to be sourced in gdb.
