### ISSUE TITLE
How to debug with the source code

### ISSUE THREAD

**Issue by 0xKira** [alset0326/peda-arm#3]
This is an excellent tool for me because I am learning debugging on Android devices.
But I don't know how to debug with the Android source code. I have AOSP source code, and I have also compiled it.
Please tell me how to use context source command.

**Comment by alset0326** [comment]
The way command `context source` finding the sources is just the same as gdb itself.
After you compile and flash the AOSP source code, you need to tell gdb where it can find the library symbol files while debugging.
You can use command `set solib-search-path` to make it.
e.g.
```bash
peda-arm > set solib-search-path aosp/out/target/product/hammerhead/symbols/system/lib/:aosp/out/target/product/hammerhead/symbols/system/lib/hw/
```
Have fun :)

**Comment by 0xKira** [comment]
It's very nice of you! That's what I'm looking for. Thanks a lot!
