### ISSUE TITLE
Termux with gdb not support peda-arm

### ISSUE THREAD

**Issue by wangmu0579** [alset0326/peda-arm#4]
peda-arm on termux with gdb have error
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word".
/data/data/com.termux/files/home/.gdbinit:1: Error in sourced command file:
:8: Error in sourced command file:
Undefined command: "from".  Try "help".
(gdb)
.seems the  problem belong to gdb  not support python on termux.
Do you have ways to solve this?

**Comment by alset0326** [comment]
peda-arm does not test on termux. But please make sure your gdb supports python.  Maybe you should compile a gdb with python from source?

**Comment by wangmu0579** [comment]
SeemS gdb now support python now. But peda still not support gdb because aarch64-linux-android? Recompile some lib needed?

gdb (GDB) 8.0.1                                            Copyright (C) 2017 Free Software Foundation, Inc.              License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>                                                 This is free software: you are free to change and redistribute it.                                                            There is NO WARRANTY, to the extent permitted by law.  Type "show copying"                                                    and "show warranty" for details.                               This GDB was configured as "aarch64-linux-android".            Type "show configuration" for configuration details.           For bug reporting instructions, please see:                    <http://www.gnu.org/software/gdb/bugs/>.                       Find the GDB manual and other documentation resources online at:                                                              <http://www.gnu.org/software/gdb/documentation/>.              For help, type "help".                                         Type "apropos word" to search for commands related to "word".  /data/data/com.termux/files/home/.gdbinit:1: Error in sourced command file:                                                   :9: Error in sourced command file:                             Undefined command: "from".  Try "help".                        (gdb) python                                                   >                                                              >print "hello"                                                 >                                                              >quit                                                          >Quit                                                          (gdb)

**Comment by wangmu0579** [comment]
ok.actually gdb still not support python :
(gdb) help python                                              Evaluate a Python command.                                                                                                    Python scripting is not supported in this copy of GDB.         This command is only a placeholder.                            (gdb)

**Comment by wangmu0579** [comment]
After compile GDB with python support. Finally I got peda-arm support Termux with AARCH64. Thanks.
But one warning exist:
# gdb --pid=1544
GNU gdb (GDB) 8.0.1
Copyright (C) 2017 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "aarch64-linux-android".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word".
[!] Warning: Cross compile toolchain not found! You can install it from https://github.com/jsnyder/arm-eabi-toolchain
[*] Loading components.
[*] Loading system calls.
[*] Loading peda main section.
[*] registering commands.

                                                             
                                                             
#####  ##### #####      #             #    #####   ##     ## 
 #   #  #  #  #   #     #             #     #   #   ##   ##  
 #   #  #     #    #   # #           # #    #   #   ##   ##  
 ####   ###   #    #   ###           ###    ####    # # # #  
 #      #     #    #  #   #  #####  #   #   #  #    # # # #  
 #      #  #  #   #   #   #         #   #   #   #   #  #  #  
###    ##### #####   ### ###       ### ### ###  ## ### # ### 
                                                             
                                                             
         alpha-0.3

Attaching to process 1544
0000| 0xffb57ab8 --> 0x0 
0004| 0xffb57abc --> 0x1 
0008| 0xffb57ac0 --> 0xffffffff 
0012| 0xffb57ac4 --> 0xd7be5b60 --> 0xe7bd0ab4 --> 0xe7bc9995 --> 0x1e4604b5 --> 0x0 
0016| 0xffb57ac8 --> 0x0 
0020| 0xffb57acc --> 0x8 
0024| 0xffb57ad0 --> 0x0 
0028| 0xffb57ad4 --> 0x0 
[---------------------------------------------------------Legend: code, data, rodata, value----------------------------------------------------------]
0xe87a0528 in __epoll_pwait () from target:/system/lib/libc.so
peda-arm > searchmem honor
[*] Searching for 'honor' in: None ranges
Found 9 results, display max 9 items:
    system@framework@boot.oat : 0x71fa3a34 ("honorOrder")
dalvik-zygote space (deleted) : 0x7748290c ("honor:/system/emui/lite:/system/global:/vendor/etc:/product/etc:/hw_oem:/cust_comm:/version/region_comm/china:/cust_spec")
              libGLES_mali.so : 0xd7122728 ("honored as resource pressure has reduced the number of threads that can run further than was requested")
              libGLES_mali.so : 0xd71227c8 ("honored as it is less than the requested workgroup size")
              libGLES_mali.so : 0xd7122838 ("honored as it is greater than the number of threads that can run on a core simultaneously")
              libGLES_mali.so : 0xd712322d ("honored. SVM fine grain buffer is not supported on the platform.")
    u:object_r:config_prop:s0 : 0xe90fe6d6 ("honor")
    u:object_r:config_prop:s0 : 0xe90fe754 ("honor")
                      [stack] : 0xffb5af42 ("honor:/system/emui/lite:/system/global:/vendor/etc:/product/etc:/hw_oem:/cust_comm:/version/region_comm/china:/cust_spec")
peda-arm >

**Comment by alset0326** [comment]
Well, this warning means assemble will be disabled.
