### ISSUE TITLE
Run peda arm on android?

### ISSUE THREAD

**Issue by wartek69** [alset0326/peda-arm#6]
Hello,
For a project I'm doing I have to retrieve a memory adress from the bss section that contains a given string on my android phone.
This sounds like a job for the searchmem feature.
The only problem I have is how to run this on my android phone, since I have to extract it from the phone's memory.
I'm entirely new in this concept so my question might be silly, anyway I hope you can help me further.

**Comment by alset0326** [comment]
Hi, usually we run `gdbserver` on the phone. And run `gdb attach remote ip:port` on pc to debug it.

**Comment by wartek69** [comment]
so if I do understand this right, by doing this I'll be able to run peda arm on my pc but it will target the phone?

**Comment by alset0326** [comment]
Yes, you are right.

**Comment by wartek69** [comment]
Thanks!
I did get it working once, next time I tried it failed.
`````
peda-arm > target remote 192.168.43.1:8888
Remote debugging using 192.168.43.1:8888
warning: while parsing target description (at line 10): Target description specified unknown architecture "arm"
warning: Could not load XML target description; ignoring
Reading /system/bin/app_process32 from remote target...
warning: File transfers from remote targets can be slow. Use "set sysroot" to access files locally instead.
Reading /system/bin/app_process32 from remote target...
Reading symbols from target:/system/bin/app_process32...(no debugging symbols found)...done.
Remote 'g' packet reply is too long: fcffffff188fcaff10000000ffffffff0000000008000000000000005a010000188fcaff4c66fbe1ffffffff0066fbe1d88ecaffc88ecaff213333f3141936f310000f60000000000000000061006c0020006c006500760065006c0020003a002000700072006500760069006f00750073003d003100200063007500720072003d0031000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000006c6f672e7461672e42004100540054004500520059005f000100000001000000000000000000000000ac00ac00ac008ca8ae18ae08aee88ca8ae18ae08aee88c00a800ac00ac00ac0080008000800080ffffffffffffffff000000000000000000000000000000000000000000000000594c06000000000011000080
```
What could be the issue of this?

**Comment by alset0326** [comment]
Your gdbserver version is incompatible with your gdb. You can download gdb and gdbserver from here https://android.googlesource.com/platform/prebuilts/gdb/linux-x86/ and https://android.googlesource.com/platform/prebuilts/misc/

**Comment by wartek69** [comment]
You sure that's the issue because I managed to run it once?
Anyway I'll try that, thanks!

**Comment by wartek69** [comment]
Got it to work, thank you very much!
You helped me out big time
